version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Update submodules
          command: |
            . venv/bin/activate
            git submodule update --init
            git submodule foreach --recursive git fetch
            git submodule foreach --recursive 'git pull origin $(git symbolic-ref --short refs/remotes/origin/HEAD | cut -d'/' -f2)'
      - save_cache:
          key: deps1-{{ .Branch }}-submodules
          paths:
            - "submodules"
      - run:
          name: Update repos.json
          command: |
            . venv/bin/activate
            make repos.json
      - add_ssh_keys:
          fingerprints:
            - "9e:f1:ce:5b:e2:34:a9:67:e0:e6:e2:34:37:7f:55:22"
      - run:
          name: Push repos.json back to repository
          command: |
              git config user.email "project.ocrd@gmail.com"
              git config user.name "OCR-D-automation-bot"
              git status --porcelain | grep -q 'repos.json' && git add repos.json && git commit -m "update repos.json [skip ci]"
              git push --set-upstream origin main
