version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Update repos.json
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .
            make repos.json
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "submodules"
            - "venv"
      - add_ssh_keys:
          fingerprints:
            - "9e:f1:ce:5b:e2:34:a9:67:e0:e6:e2:34:37:7f:55:22"
      - run:
          name: Push repos.json as well as dependency information back to repository
          command: |
              git config user.email "project.ocrd@gmail.com"
              git config user.name "OCR-D-automation-bot"
              git status --porcelain | grep -q 'repos.json' && git add repos.json && git add deps.json && git add dep_conflicts.json && git add core_deps.txt && git commit -m "update files [skip ci]"
              git push --set-upstream origin main
